---
apiVersion: v1
kind: Secret
metadata:
  name: mirwin77-mirwin77-poi-map-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23Janus1/mirwin77-frontend-gitops
